env:
  map_path: maps/8x8/basesWorkers8x8.xml
  max_steps: 2000
  interval: 100
  record_video: true
  display: false

agents:
  - player_id: 0
    model: Qwen2.5-72B-Instruct
    temperature: 0
    max_tokens: 8192
    prompt: few-shot-w-strategy
    strategy: ace/data/strategies/strategy_1.json
  - player_id: 1
    model: Qwen2.5-72B-Instruct
    temperature: 0
    max_tokens: 8192
    prompt: few-shot-w-strategy
    strategy: ace/data/opponents/strategy_1.json

best_of_n: 3